import type { Metadata } from "next";

import localFont from "next/font/local";

import StyledComponentsRegistry from "@/lib/registry";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppinsFont = localFont({
  src: [
    {
      path: "../../public/fonts/poppins-v21-latin-300.woff2",
    },
    {
      path: "../../public/fonts/poppins-v21-latin-600.woff2",
    },
    {
      path: "../../public/fonts/poppins-v21-latin-regular.woff2",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppinsFont.className}>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
